# fly.toml app configuration file generated for rmse-lenslocked on 2025-04-02T00:46:21+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rmse-lenslocked'
primary_region = 'otp'

[build]
  [build.args]
    GO_VERSION = '1.24.1'

[env]
  PORT = '3000'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
